name: ZAP Full Scan

on:
  workflow_dispatch:   # manual trigger only (for safety)

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "http://juice-shop.herokuapp.com"
          format: "html"
          output: "zap-fullscan-report.html"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-fullscan-report
          path: zap-fullscan-report.html
